language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
  - composer install
script:
  - vendor/bin/phpcs src tests --standard=PSR2 -p
  - vendor/bin/phpunit
after_script:
  - vendor/bin/test-reporter
